title: "Dr Lukas F Lang"
author: "Dr Lukas F Lang"
description: "Passionate about maths, science, and data"
permalink: /blog/:year/:month/:day/:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B, %Y"
paginate: 5
paginate_path: /blog/page/:num/

# Layout
show_social: true          # show site description and social links in the footer
show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu
navigation:
  - {file: "index.html", icon: home}
  - {file: "cv.md", icon: scroll}
  - {file: "publications.md", icon: scroll}

external:                  # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:contact@lukaslang.eu"}
  - {title: LinkedIn, icon: linkedin, url: "https://linkedin.com/in/lukaslang"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/lukaslang"}
  - {title: Github, icon: github, url: "https://github.com/lukaslang"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-paginate
 
